### ISSUE TITLE
[Refactor] JWT 검증 시 DB 접근 최소화

### ISSUE THREAD

**Issue by jihyunk03** [BeyondPong/Backend#132]
### discription
기존에는 JWT 검증하는 미들웨어에서 DB에서 객체를 찾아서 request에 user를 넣어주는 방식이었는데 이렇게 되면 모든 api 마다 DB에 접근하게 됨
DB에 접근하는 대신 user에 jwt로부터 받은 필요한 정보만을 담아서 임시 객체를 만들어서 보내주는 형식으로 변경
외부 api에서는 DB 접근이 필요한 경우 내부에서 접근하고 있으므로 JWT 검증 단계에서는 없애고 로그인 시에만 DB에 접근하도록 변경

### todo
- [ ] DB 접근 대신 임시 객체 생성해서 반환
- [ ] 로그인 시 DB로 확인하는지 체크해서 그 부분에서 진행하도록 추가
- [x] JWT 검증 시, 다중 로그인 url 예외부분 추가
