### ISSUE TITLE
[Feat] 로그인 jwt 구현

### ISSUE THREAD

**Issue by jihyunk03** [BeyondPong/Backend#37]
### 현재 상황
- access token으로 사용자의 정보를 가져옴
- refresh token 발급만 되어 있는 상황

### TODO
- [x] 이미 있는 사용자인지 확인
- [x] 회원 가입 -> 데이터베이스에 저장
- [x] jwt 인증 인가 적용
- [x] 필요한 사용자 정보만 FE로 보내기
