### ISSUE TITLE
[Feat] 회원가입 여부 api 추가

### ISSUE THREAD

**Issue by jihyunk03** [BeyondPong/Backend#69]
### todo
- [x]  jwt 검사 시, url로 확인(예외 처리)
- [x]  기존 로그인 코드에서 장고 캐시 사용해서 닉네임과 함께 상태 저장
- [x]  api 요청 시 확인해서 있으면 `new_user`로, 없으면 `origin_user`로 보내고 삭제
