### ISSUE TITLE
[Feat] 게임 재시작 로직 추가

### ISSUE THREAD

**Issue by jihyunk03** [BeyondPong/Backend#80]
### todo
- [x] action == restart_game 로직 추가
- [x] update_score에서 ball_position 초기화 했던 부분 옮기기 (restart_game)
- [x] self.running으로 while 돌리는데 다시 게임 시작할 때 이전꺼 종료시키고 다시 새로 시작할 수 있도록 로직 추가
